import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "HSZ Engineering Solutions - High Quality Industrial & Consumer Products",
  description:
    "HSZ Engineering Solutions provides top-quality industrial and consumer products with exceptional customer service. Explore our range of products, get quotes, and experience excellence.",
keywords: [
  // General Industrial & Engineering (Australia-focused)
  "industrial products Australia",
  "engineering solutions Australia",
  "consumer products Australia",
  "industrial equipment Australia",
  "high-quality industrial products Australia",
  "custom products Australia",
  "manufacturing solutions Australia",
  "engineering services Australia",
  "industrial supply Australia",
  "automation equipment Australia",
  "precision tools Australia",
  "mechanical products Australia",
  "industrial machinery Australia",
  "technical solutions Australia",
  "industrial safety Australia",
  "industrial components Australia",
  "industrial accessories Australia",
  "industrial parts Australia",
  "engineering support Australia",
  "industrial technology Australia",
  "industrial innovation Australia",
  "industrial solutions Australia",
  "industrial services Australia",
  "industrial manufacturing Australia",
  "industrial design Australia",
  "industrial supply chain Australia",
  "engineering consultancy Australia",
  "industrial maintenance Australia",
  "engineering products Australia",
  "industrial engineering Australia",
  "consumer electronics Australia",
  "industrial automation Australia",
  "industrial robotics Australia",
  "industrial automation solutions Australia",
  "mechanical engineering Australia",
  "industrial quality control Australia",
  "industrial packaging Australia",
  "industrial logistics Australia",
  "industrial fabrication Australia",
  "industrial assembly Australia",
  "industrial installation Australia",
  "industrial tools Australia",
  "industrial safety equipment Australia",
  "industrial standards Australia",
  "engineering projects Australia",
  "industrial components supplier Australia",
  "industrial machinery supplier Australia",
  "industrial spare parts Australia",
  "custom manufacturing Australia",
  "industrial solutions provider Australia",
  "industrial consultancy Australia",
  "industrial tech solutions Australia",
  "industrial optimization Australia",
  "engineering innovation Australia",
  "technical support Australia",
  "industrial efficiency Australia",
  "industrial processes Australia",
  "industrial performance Australia",
  "engineering quality Australia",
  "industrial consulting Australia",
  "industrial design services Australia",
  "industrial product development Australia",
  "industrial solutions company Australia",
  "engineering excellence Australia",
  "industrial supply solutions Australia",
  "industrial process improvement Australia",
  "engineering project management Australia",
  "industrial automation tools Australia",
  "engineering precision Australia",
  "industrial engineering services Australia",
  "consumer product solutions Australia",
  "industrial supply chain management Australia",
  "industrial sourcing Australia",
  "engineering expertise Australia",
  "technical products Australia",
  "industrial systems Australia",
  "engineering consultancy services Australia",
  "industrial digital solutions Australia",
  "industrial maintenance services Australia",
  "industrial tech innovations Australia",
  "engineering and design Australia",
  "industrial equipment supplier Australia",
  "engineering solutions company Australia",
  "industrial product supplier Australia",
  "custom engineering solutions Australia",
  "industrial solutions expert Australia",
  "industrial machinery solutions Australia",
  "engineering technology Australia",
  "industrial automation supplier Australia",
  "industrial robotics solutions Australia",
  "industrial product development Australia",
  "industrial efficiency tools Australia",
  "engineering service provider Australia",
  "industrial performance optimization Australia",
  "industrial design engineering Australia",
  "industrial innovation solutions Australia",
  "industrial quality products Australia",
  "engineering technical services Australia",
  "industrial logistics solutions Australia",
  "industrial manufacturing solutions Australia",
  "industrial tools supplier Australia",

  // Specific Tools Keywords
  "industrial hand tools Australia",
  "power tools Australia",
  "electric tools Australia",
  "mechanical tools Australia",
  "engineering tools Australia",
  "construction tools Australia",
  "industrial cutting tools Australia",
  "industrial measuring tools Australia",
  "industrial workshop tools Australia",
  "industrial precision tools Australia",
  "industrial repair tools Australia",
  "industrial safety tools Australia",
  "mechanical hand tools Australia",
  "automotive tools Australia",
  "industrial assembly tools Australia",
  "industrial maintenance tools Australia",
  "industrial fabrication tools Australia",
  "industrial installation tools Australia",
  "industrial testing tools Australia",
  "industrial calibration tools Australia",
  "industrial inspection tools Australia",
  "industrial engineering tools Australia",
  "professional tools Australia",
  "industrial construction tools Australia",
  "engineering workshop tools Australia",
  "industrial manufacturing tools Australia",
  "industrial electronics tools Australia",
  "industrial lab tools Australia",
  "industrial robotics tools Australia",
  "industrial automation tools Australia",
  "industrial cleaning tools Australia",
  "industrial welding tools Australia",
  "industrial plumbing tools Australia",
  "industrial metalworking tools Australia",
  "industrial woodworking tools Australia",
  "industrial painting tools Australia",
  "industrial garden tools Australia",
  "industrial carpentry tools Australia",
  "industrial electrical tools Australia",

  // Additional Australia Local & Regional Keywords
  "Sydney industrial products",
  "Melbourne engineering solutions",
  "Brisbane industrial equipment",
  "Perth industrial tools",
  "Adelaide manufacturing solutions",
  "Gold Coast consumer products",
  "Canberra industrial supplier",
  "Hobart engineering consultancy",
  "Darwin industrial services",
  "Australia industrial machinery supplier",
  "Australian industrial tools supplier",
  "custom manufacturing Sydney",
  "engineering services Melbourne",
  "industrial automation Brisbane",
  "precision tools Perth",
  "mechanical products Adelaide",
  "industrial robotics Gold Coast",
  "industrial supply Canberra",
  "industrial components Hobart",
  "industrial spare parts Darwin",

  // Mix more variations to reach 500+
  "industrial equipment online Australia",
  "engineering solutions company Sydney",
  "industrial products wholesale Australia",
  "industrial machinery online Australia",
  "buy industrial tools Australia",
  "high-quality industrial machinery Australia",
  "industrial spare parts supplier Australia",
  "engineering support services Australia",
  "industrial automation solutions company Australia",
  "industrial assembly services Australia",
  "custom industrial solutions Australia",
  "industrial fabrication company Australia",
  "industrial logistics company Australia",
  "industrial process solutions Australia",
  "industrial product manufacturer Australia",
  "industrial workshop supplier Australia",
  "engineering consulting Australia",
  "industrial product supplier Melbourne",
  "industrial tools retailer Australia",
  "industrial machinery retailer Australia",
  "precision engineering tools Australia",
  "mechanical engineering supplier Australia",
  "industrial robotics company Australia",
  "industrial automation provider Australia",
  "industrial safety solutions Australia",
  "industrial inspection tools Australia",
  "industrial quality control services Australia",
  "industrial electronics supplier Australia",
  "industrial lab equipment Australia",
  "industrial technology solutions Australia",
  "engineering product design Australia",
  "industrial solutions for businesses Australia",
  "industrial supply chain provider Australia",
  "industrial consulting services Australia",
  "engineering service provider Sydney",
  "industrial product logistics Australia",
  "industrial tools online store Australia",
  "industrial assembly tools supplier Australia",
  "industrial machinery maintenance Australia",
  "industrial maintenance services provider Australia",
  "industrial engineering consulting Australia",
  "industrial innovation solutions company Australia",
  "industrial process optimization Australia",
  "industrial product solutions provider Australia",
  "industrial product development services Australia",
  "industrial systems supplier Australia",
  "engineering precision tools Australia",
  "industrial products export Australia",
  "industrial supplier near me Australia",
  "industrial services Melbourne",
  "industrial automation engineering Australia",
  "industrial robotics engineering Australia",
  "industrial tools wholesale Australia",
  "industrial machinery solutions provider Australia",
  "industrial engineering company Sydney",
  "industrial products online store Australia",
  "industrial components retailer Australia",
  "industrial machinery parts Australia",
  "industrial assembly services Melbourne",
  "industrial fabrication supplier Australia",
  "industrial engineering design Australia",
  "industrial consulting Melbourne",
  "industrial workshop equipment Australia",
  "industrial power tools supplier Australia",
  "industrial mechanical tools Australia",
  "industrial electrical tools supplier Australia",
  "industrial engineering maintenance Australia",
  "industrial robotics parts Australia",
  "industrial automation parts Australia",
  "industrial tools supplier Sydney",
  "industrial machinery supplier Melbourne",
  "industrial engineering services Brisbane",
  "industrial automation engineering Sydney",
  "industrial manufacturing supplier Australia",
  "industrial precision tools Melbourne",
  "industrial mechanical tools Brisbane",
  "industrial electrical tools Perth",
  "industrial safety tools Melbourne",
  "industrial inspection equipment Australia",
  "industrial electronics tools Australia",
  "industrial automation services Australia",
  "industrial robotics supplier Melbourne",
  "industrial machinery supplier Adelaide",
  "industrial equipment retailer Australia",
  "industrial tools solutions Australia",
  "industrial machinery solutions Sydney",
  "industrial tools services Australia",
  "industrial components supplier Melbourne",
  "industrial parts retailer Australia",
  "industrial engineering consulting Sydney",
  "industrial automation systems Australia",
  "industrial robotics solutions Melbourne",
  "industrial machinery solutions Brisbane",
  "industrial engineering company Melbourne",
  "industrial tools online Melbourne",
  "industrial equipment online Sydney",
  "industrial spare parts Melbourne",
  "industrial tools online Perth",
  "industrial automation equipment Brisbane",
  "industrial machinery maintenance Melbourne",
  "industrial tools supplier Adelaide",
  "industrial engineering supplier Perth",
  "industrial fabrication solutions Melbourne",
  "industrial engineering solutions Brisbane",
  "industrial tools distributor Australia",
  "industrial automation provider Sydney",
  "industrial robotics company Melbourne",
  "industrial machinery distributor Australia"
],

  icons: {
    icon: "/logotitle.png",
  },
  openGraph: {
    type: "website",
    url: "https://www.hszengineering.solutions",
    title: "HSZ Engineering Solutions - High Quality Industrial & Consumer Products",
    description:
      "Explore HSZ Engineering Solutions for top-quality industrial and consumer products, exceptional service, and reliable engineering solutions.",
    images: [
      {
        url: "/logotitle.png",
        width: 800,
        height: 600,
        alt: "HSZ Engineering Solutions Logo",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    site: "@HSZEngineering",
    title: "HSZ Engineering Solutions - Industrial & Consumer Products",
    description:
      "HSZ Engineering Solutions offers high-quality products, customer-focused solutions, and reliable engineering services.",
    images: ["/logotitle.png"],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
